# Generated by Django 4.0.6 on 2025-03-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrailleText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('braille', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HandwrittenImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('extracted_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
