# Generated by Django 4.2 on 2025-05-09 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('converter', '0002_audiofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBotQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('audio_file', 'Audio File'), ('recording', 'Live Recording')], max_length=20)),
                ('output_type', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('braille', 'Braille')], max_length=20)),
                ('text_input', models.TextField(blank=True, null=True)),
                ('audio_input', models.FileField(blank=True, null=True, upload_to='chatbot_audio_inputs/')),
                ('recording_input', models.TextField(blank=True, null=True)),
                ('llm_response', models.TextField(blank=True, null=True)),
                ('audio_response', models.FileField(blank=True, null=True, upload_to='chatbot_audio_responses/')),
                ('braille_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
